services:
  - type: web
    name: trackure-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.mjs
    envVars:
      - key: NODE_ENV
        value: production